development:
  adapter: mysql2
  user: root
  password: root
  database: db/zertico-cloud-dev
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  user: root
  password: root
  database: db/zertico-cloud-test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  user: root
  password: root
  database: db/zertico-cloud-prod
  pool: 5
  timeout: 5000

cucumber:
  <<: *test